services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: bu1_portal_db
      MYSQL_USER: bu1_admin
      MYSQL_PASSWORD: bu1_secure_pass
      MYSQL_ROOT_PASSWORD: bu1_root_secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: bu1_admin
      WORDPRESS_DB_PASSWORD: bu1_secure_pass
      WORDPRESS_DB_NAME: bu1_portal_db
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_ui
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: bu1_root_secret
    depends_on:
      - db
    networks:
      - webnet
      
  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      wordpress:
        condition: service_healthy
      phpmyadmin:
        condition: service_started
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
    driver: bridge